var data = [
    {
        id:1,
        name:"",
        price:"",
        description:"",
        img:"",
        specification:[
            {
                id:1,
                keySpec:{
                    id:1,
                    ram:"",
                    Processor:"",
                    RearCamera:"",
                    FrontCamera:"",
                    Battery:"",
                    Display:""
                },
                General:{
                    id:2,
                    LaunchDate:"",
                    OperatingSystem:"",
                    CustomUI:""
                },
                Performance:{
                    id:3,
                    Chipset:"",
                    CPU:"",
                    Architecture:"",
                    Fabrication:"",
                    Graphics:"",
                    RAM:"",
                    RAMType:""
                },
                Display:{
                    id:4,
                    DisplayType:"",
                    ScreenSize:"",
                    Resolution:"",
                    AspectRatio:"",
                    PixelDensity:"",
                    ScreentoBodyRatio:"",
                    ScreenProtection:"",
                    BezelLessdisplay:"",
                    TouchScreen:"",
                    Brightness:"",
                    HDR10HDRsupport:"",
                    RefreshRate:"",
                },
                Design:{
                    id:5,
                    Height:"",
                    Width:"",
                    Thickness:"",
                    Weight:"",
                    BuildMaterial:"",
                    Colours:"",
                    Waterproof:"",
                    Ruggedness:""
                },
                Camera:{
                    id:6,
                    CameraSetup:"",
                    VideoRecording:"",
                    Autofocus:""
                },
                Battery:{
                    id:7,
                    Capacity:"",
                    Type:"",
                    Removable:"",
                    TalkTime:"",
                    WirelessCharging:"",
                    QuickCharging:"",
                    USBTypeC:"",
                },
                Storage:{
                    id:8,
                    InternalMemory:"",
                    ExpandableMemory:"",
                    UserAvailableStorage:"",
                    USBOTG:"",
                    StorageType:""
                },
                NetworkConnectivity:{
                    id:9,
                    SIMSlot:"",
                    SIMSize:"",
                    NetworkSupport:"",
                    VoLTE:"",
                    SIM:"",
                    WiFi:"",
                    Bluetooth:"",
                    GPS:"",
                    NFC:"",
                    USBConnectivity:""
                },
                Multimedia:{
                    id:10,
                    FMRadio:"",
                    Loudspeaker:"",
                    AudioJack:""
                },
                Sensors:{
                    id:11,
                    FingerprintSensor:"",
                }
            }
        ]
    },
    {
        id:2,
        name:"",
        price:"",
        description:"",
        img:"",
        specification:[
            {
                id:1,
                keySpec:{
                    id:1,
                    ram:"",
                    Processor:"",
                    RearCamera:"",
                    FrontCamera:"",
                    Battery:"",
                    Display:""
                },
                General:{
                    id:2,
                    LaunchDate:"",
                    OperatingSystem:"",
                    CustomUI:""
                },
                Performance:{
                    id:3,
                    Chipset:"",
                    CPU:"",
                    Architecture:"",
                    Fabrication:"",
                    Graphics:"",
                    RAM:"",
                    RAMType:""
                },
                Display:{
                    id:4,
                    DisplayType:"",
                    ScreenSize:"",
                    Resolution:"",
                    AspectRatio:"",
                    PixelDensity:"",
                    ScreentoBodyRatio:"",
                    ScreenProtection:"",
                    BezelLessdisplay:"",
                    TouchScreen:"",
                    Brightness:"",
                    HDR10HDRsupport:"",
                    RefreshRate:"",
                },
                Design:{
                    id:5,
                    Height:"",
                    Width:"",
                    Thickness:"",
                    Weight:"",
                    BuildMaterial:"",
                    Colours:"",
                    Waterproof:"",
                    Ruggedness:""
                },
                Camera:{
                    id:6,
                    CameraSetup:"",
                    VideoRecording:"",
                    Autofocus:""
                },
                Battery:{
                    id:7,
                    Capacity:"",
                    Type:"",
                    Removable:"",
                    TalkTime:"",
                    WirelessCharging:"",
                    QuickCharging:"",
                    USBTypeC:"",
                },
                Storage:{
                    id:8,
                    InternalMemory:"",
                    ExpandableMemory:"",
                    UserAvailableStorage:"",
                    USBOTG:"",
                    StorageType:""
                },
                NetworkConnectivity:{
                    id:9,
                    SIMSlot:"",
                    SIMSize:"",
                    NetworkSupport:"",
                    VoLTE:"",
                    SIM:"",
                    WiFi:"",
                    Bluetooth:"",
                    GPS:"",
                    NFC:"",
                    USBConnectivity:""
                },
                Multimedia:{
                    id:10,
                    FMRadio:"",
                    Loudspeaker:"",
                    AudioJack:""
                },
                Sensors:{
                    id:11,
                    FingerprintSensor:"",
                }
            }
        ]
    },
    {
        id:3,
        name:"",
        price:"",
        description:"",
        img:"",
        specification:[
            {
                id:1,
                keySpec:{
                    id:1,
                    ram:"",
                    Processor:"",
                    RearCamera:"",
                    FrontCamera:"",
                    Battery:"",
                    Display:""
                },
                General:{
                    id:2,
                    LaunchDate:"",
                    OperatingSystem:"",
                    CustomUI:""
                },
                Performance:{
                    id:3,
                    Chipset:"",
                    CPU:"",
                    Architecture:"",
                    Fabrication:"",
                    Graphics:"",
                    RAM:"",
                    RAMType:""
                },
                Display:{
                    id:4,
                    DisplayType:"",
                    ScreenSize:"",
                    Resolution:"",
                    AspectRatio:"",
                    PixelDensity:"",
                    ScreentoBodyRatio:"",
                    ScreenProtection:"",
                    BezelLessdisplay:"",
                    TouchScreen:"",
                    Brightness:"",
                    HDR10HDRsupport:"",
                    RefreshRate:"",
                },
                Design:{
                    id:5,
                    Height:"",
                    Width:"",
                    Thickness:"",
                    Weight:"",
                    BuildMaterial:"",
                    Colours:"",
                    Waterproof:"",
                    Ruggedness:""
                },
                Camera:{
                    id:6,
                    CameraSetup:"",
                    VideoRecording:"",
                    Autofocus:""
                },
                Battery:{
                    id:7,
                    Capacity:"",
                    Type:"",
                    Removable:"",
                    TalkTime:"",
                    WirelessCharging:"",
                    QuickCharging:"",
                    USBTypeC:"",
                },
                Storage:{
                    id:8,
                    InternalMemory:"",
                    ExpandableMemory:"",
                    UserAvailableStorage:"",
                    USBOTG:"",
                    StorageType:""
                },
                NetworkConnectivity:{
                    id:9,
                    SIMSlot:"",
                    SIMSize:"",
                    NetworkSupport:"",
                    VoLTE:"",
                    SIM:"",
                    WiFi:"",
                    Bluetooth:"",
                    GPS:"",
                    NFC:"",
                    USBConnectivity:""
                },
                Multimedia:{
                    id:10,
                    FMRadio:"",
                    Loudspeaker:"",
                    AudioJack:""
                },
                Sensors:{
                    id:11,
                    FingerprintSensor:"",
                }
            }
        ]
    },
    {
        id:4,
        name:"",
        price:"",
        description:"",
        img:"",
        specification:[
            {
                id:1,
                keySpec:{
                    id:1,
                    ram:"",
                    Processor:"",
                    RearCamera:"",
                    FrontCamera:"",
                    Battery:"",
                    Display:""
                },
                General:{
                    id:2,
                    LaunchDate:"",
                    OperatingSystem:"",
                    CustomUI:""
                },
                Performance:{
                    id:3,
                    Chipset:"",
                    CPU:"",
                    Architecture:"",
                    Fabrication:"",
                    Graphics:"",
                    RAM:"",
                    RAMType:""
                },
                Display:{
                    id:4,
                    DisplayType:"",
                    ScreenSize:"",
                    Resolution:"",
                    AspectRatio:"",
                    PixelDensity:"",
                    ScreentoBodyRatio:"",
                    ScreenProtection:"",
                    BezelLessdisplay:"",
                    TouchScreen:"",
                    Brightness:"",
                    HDR10HDRsupport:"",
                    RefreshRate:"",
                },
                Design:{
                    id:5,
                    Height:"",
                    Width:"",
                    Thickness:"",
                    Weight:"",
                    BuildMaterial:"",
                    Colours:"",
                    Waterproof:"",
                    Ruggedness:""
                },
                Camera:{
                    id:6,
                    CameraSetup:"",
                    VideoRecording:"",
                    Autofocus:""
                },
                Battery:{
                    id:7,
                    Capacity:"",
                    Type:"",
                    Removable:"",
                    TalkTime:"",
                    WirelessCharging:"",
                    QuickCharging:"",
                    USBTypeC:"",
                },
                Storage:{
                    id:8,
                    InternalMemory:"",
                    ExpandableMemory:"",
                    UserAvailableStorage:"",
                    USBOTG:"",
                    StorageType:""
                },
                NetworkConnectivity:{
                    id:9,
                    SIMSlot:"",
                    SIMSize:"",
                    NetworkSupport:"",
                    VoLTE:"",
                    SIM:"",
                    WiFi:"",
                    Bluetooth:"",
                    GPS:"",
                    NFC:"",
                    USBConnectivity:""
                },
                Multimedia:{
                    id:10,
                    FMRadio:"",
                    Loudspeaker:"",
                    AudioJack:""
                },
                Sensors:{
                    id:11,
                    FingerprintSensor:"",
                }
            }
        ]
    },
    {
        id:5,
        name:"",
        price:"",
        description:"",
        img:"",
        specification:[
            {
                id:1,
                keySpec:{
                    id:1,
                    ram:"",
                    Processor:"",
                    RearCamera:"",
                    FrontCamera:"",
                    Battery:"",
                    Display:""
                },
                General:{
                    id:2,
                    LaunchDate:"",
                    OperatingSystem:"",
                    CustomUI:""
                },
                Performance:{
                    id:3,
                    Chipset:"",
                    CPU:"",
                    Architecture:"",
                    Fabrication:"",
                    Graphics:"",
                    RAM:"",
                    RAMType:""
                },
                Display:{
                    id:4,
                    DisplayType:"",
                    ScreenSize:"",
                    Resolution:"",
                    AspectRatio:"",
                    PixelDensity:"",
                    ScreentoBodyRatio:"",
                    ScreenProtection:"",
                    BezelLessdisplay:"",
                    TouchScreen:"",
                    Brightness:"",
                    HDR10HDRsupport:"",
                    RefreshRate:"",
                },
                Design:{
                    id:5,
                    Height:"",
                    Width:"",
                    Thickness:"",
                    Weight:"",
                    BuildMaterial:"",
                    Colours:"",
                    Waterproof:"",
                    Ruggedness:""
                },
                Camera:{
                    id:6,
                    CameraSetup:"",
                    VideoRecording:"",
                    Autofocus:""
                },
                Battery:{
                    id:7,
                    Capacity:"",
                    Type:"",
                    Removable:"",
                    TalkTime:"",
                    WirelessCharging:"",
                    QuickCharging:"",
                    USBTypeC:"",
                },
                Storage:{
                    id:8,
                    InternalMemory:"",
                    ExpandableMemory:"",
                    UserAvailableStorage:"",
                    USBOTG:"",
                    StorageType:""
                },
                NetworkConnectivity:{
                    id:9,
                    SIMSlot:"",
                    SIMSize:"",
                    NetworkSupport:"",
                    VoLTE:"",
                    SIM:"",
                    WiFi:"",
                    Bluetooth:"",
                    GPS:"",
                    NFC:"",
                    USBConnectivity:""
                },
                Multimedia:{
                    id:10,
                    FMRadio:"",
                    Loudspeaker:"",
                    AudioJack:""
                },
                Sensors:{
                    id:11,
                    FingerprintSensor:"",
                }
            }
        ]
    },
    {
        id:6,
        name:"",
        price:"",
        description:"",
        img:"",
        specification:[
            {
                id:1,
                keySpec:{
                    id:1,
                    ram:"",
                    Processor:"",
                    RearCamera:"",
                    FrontCamera:"",
                    Battery:"",
                    Display:""
                },
                General:{
                    id:2,
                    LaunchDate:"",
                    OperatingSystem:"",
                    CustomUI:""
                },
                Performance:{
                    id:3,
                    Chipset:"",
                    CPU:"",
                    Architecture:"",
                    Fabrication:"",
                    Graphics:"",
                    RAM:"",
                    RAMType:""
                },
                Display:{
                    id:4,
                    DisplayType:"",
                    ScreenSize:"",
                    Resolution:"",
                    AspectRatio:"",
                    PixelDensity:"",
                    ScreentoBodyRatio:"",
                    ScreenProtection:"",
                    BezelLessdisplay:"",
                    TouchScreen:"",
                    Brightness:"",
                    HDR10HDRsupport:"",
                    RefreshRate:"",
                },
                Design:{
                    id:5,
                    Height:"",
                    Width:"",
                    Thickness:"",
                    Weight:"",
                    BuildMaterial:"",
                    Colours:"",
                    Waterproof:"",
                    Ruggedness:""
                },
                Camera:{
                    id:6,
                    CameraSetup:"",
                    VideoRecording:"",
                    Autofocus:""
                },
                Battery:{
                    id:7,
                    Capacity:"",
                    Type:"",
                    Removable:"",
                    TalkTime:"",
                    WirelessCharging:"",
                    QuickCharging:"",
                    USBTypeC:"",
                },
                Storage:{
                    id:8,
                    InternalMemory:"",
                    ExpandableMemory:"",
                    UserAvailableStorage:"",
                    USBOTG:"",
                    StorageType:""
                },
                NetworkConnectivity:{
                    id:9,
                    SIMSlot:"",
                    SIMSize:"",
                    NetworkSupport:"",
                    VoLTE:"",
                    SIM:"",
                    WiFi:"",
                    Bluetooth:"",
                    GPS:"",
                    NFC:"",
                    USBConnectivity:""
                },
                Multimedia:{
                    id:10,
                    FMRadio:"",
                    Loudspeaker:"",
                    AudioJack:""
                },
                Sensors:{
                    id:11,
                    FingerprintSensor:"",
                }
            }
        ]
    },
    {
        id:7,
        name:"",
        price:"",
        description:"",
        img:"",
        specification:[
            {
                id:1,
                keySpec:{
                    id:1,
                    ram:"",
                    Processor:"",
                    RearCamera:"",
                    FrontCamera:"",
                    Battery:"",
                    Display:""
                },
                General:{
                    id:2,
                    LaunchDate:"",
                    OperatingSystem:"",
                    CustomUI:""
                },
                Performance:{
                    id:3,
                    Chipset:"",
                    CPU:"",
                    Architecture:"",
                    Fabrication:"",
                    Graphics:"",
                    RAM:"",
                    RAMType:""
                },
                Display:{
                    id:4,
                    DisplayType:"",
                    ScreenSize:"",
                    Resolution:"",
                    AspectRatio:"",
                    PixelDensity:"",
                    ScreentoBodyRatio:"",
                    ScreenProtection:"",
                    BezelLessdisplay:"",
                    TouchScreen:"",
                    Brightness:"",
                    HDR10HDRsupport:"",
                    RefreshRate:"",
                },
                Design:{
                    id:5,
                    Height:"",
                    Width:"",
                    Thickness:"",
                    Weight:"",
                    BuildMaterial:"",
                    Colours:"",
                    Waterproof:"",
                    Ruggedness:""
                },
                Camera:{
                    id:6,
                    CameraSetup:"",
                    VideoRecording:"",
                    Autofocus:""
                },
                Battery:{
                    id:7,
                    Capacity:"",
                    Type:"",
                    Removable:"",
                    TalkTime:"",
                    WirelessCharging:"",
                    QuickCharging:"",
                    USBTypeC:"",
                },
                Storage:{
                    id:8,
                    InternalMemory:"",
                    ExpandableMemory:"",
                    UserAvailableStorage:"",
                    USBOTG:"",
                    StorageType:""
                },
                NetworkConnectivity:{
                    id:9,
                    SIMSlot:"",
                    SIMSize:"",
                    NetworkSupport:"",
                    VoLTE:"",
                    SIM:"",
                    WiFi:"",
                    Bluetooth:"",
                    GPS:"",
                    NFC:"",
                    USBConnectivity:""
                },
                Multimedia:{
                    id:10,
                    FMRadio:"",
                    Loudspeaker:"",
                    AudioJack:""
                },
                Sensors:{
                    id:11,
                    FingerprintSensor:"",
                }
            }
        ]
    },
    {
        id:8,
        name:"",
        price:"",
        description:"",
        img:"",
        specification:[
            {
                id:1,
                keySpec:{
                    id:1,
                    ram:"",
                    Processor:"",
                    RearCamera:"",
                    FrontCamera:"",
                    Battery:"",
                    Display:""
                },
                General:{
                    id:2,
                    LaunchDate:"",
                    OperatingSystem:"",
                    CustomUI:""
                },
                Performance:{
                    id:3,
                    Chipset:"",
                    CPU:"",
                    Architecture:"",
                    Fabrication:"",
                    Graphics:"",
                    RAM:"",
                    RAMType:""
                },
                Display:{
                    id:4,
                    DisplayType:"",
                    ScreenSize:"",
                    Resolution:"",
                    AspectRatio:"",
                    PixelDensity:"",
                    ScreentoBodyRatio:"",
                    ScreenProtection:"",
                    BezelLessdisplay:"",
                    TouchScreen:"",
                    Brightness:"",
                    HDR10HDRsupport:"",
                    RefreshRate:"",
                },
                Design:{
                    id:5,
                    Height:"",
                    Width:"",
                    Thickness:"",
                    Weight:"",
                    BuildMaterial:"",
                    Colours:"",
                    Waterproof:"",
                    Ruggedness:""
                },
                Camera:{
                    id:6,
                    CameraSetup:"",
                    VideoRecording:"",
                    Autofocus:""
                },
                Battery:{
                    id:7,
                    Capacity:"",
                    Type:"",
                    Removable:"",
                    TalkTime:"",
                    WirelessCharging:"",
                    QuickCharging:"",
                    USBTypeC:"",
                },
                Storage:{
                    id:8,
                    InternalMemory:"",
                    ExpandableMemory:"",
                    UserAvailableStorage:"",
                    USBOTG:"",
                    StorageType:""
                },
                NetworkConnectivity:{
                    id:9,
                    SIMSlot:"",
                    SIMSize:"",
                    NetworkSupport:"",
                    VoLTE:"",
                    SIM:"",
                    WiFi:"",
                    Bluetooth:"",
                    GPS:"",
                    NFC:"",
                    USBConnectivity:""
                },
                Multimedia:{
                    id:10,
                    FMRadio:"",
                    Loudspeaker:"",
                    AudioJack:""
                },
                Sensors:{
                    id:11,
                    FingerprintSensor:"",
                }
            }
        ]
    },
    {
        id:9,
        name:"",
        price:"",
        description:"",
        img:"",
        specification:[
            {
                id:1,
                keySpec:{
                    id:1,
                    ram:"",
                    Processor:"",
                    RearCamera:"",
                    FrontCamera:"",
                    Battery:"",
                    Display:""
                },
                General:{
                    id:2,
                    LaunchDate:"",
                    OperatingSystem:"",
                    CustomUI:""
                },
                Performance:{
                    id:3,
                    Chipset:"",
                    CPU:"",
                    Architecture:"",
                    Fabrication:"",
                    Graphics:"",
                    RAM:"",
                    RAMType:""
                },
                Display:{
                    id:4,
                    DisplayType:"",
                    ScreenSize:"",
                    Resolution:"",
                    AspectRatio:"",
                    PixelDensity:"",
                    ScreentoBodyRatio:"",
                    ScreenProtection:"",
                    BezelLessdisplay:"",
                    TouchScreen:"",
                    Brightness:"",
                    HDR10HDRsupport:"",
                    RefreshRate:"",
                },
                Design:{
                    id:5,
                    Height:"",
                    Width:"",
                    Thickness:"",
                    Weight:"",
                    BuildMaterial:"",
                    Colours:"",
                    Waterproof:"",
                    Ruggedness:""
                },
                Camera:{
                    id:6,
                    CameraSetup:"",
                    VideoRecording:"",
                    Autofocus:""
                },
                Battery:{
                    id:7,
                    Capacity:"",
                    Type:"",
                    Removable:"",
                    TalkTime:"",
                    WirelessCharging:"",
                    QuickCharging:"",
                    USBTypeC:"",
                },
                Storage:{
                    id:8,
                    InternalMemory:"",
                    ExpandableMemory:"",
                    UserAvailableStorage:"",
                    USBOTG:"",
                    StorageType:""
                },
                NetworkConnectivity:{
                    id:9,
                    SIMSlot:"",
                    SIMSize:"",
                    NetworkSupport:"",
                    VoLTE:"",
                    SIM:"",
                    WiFi:"",
                    Bluetooth:"",
                    GPS:"",
                    NFC:"",
                    USBConnectivity:""
                },
                Multimedia:{
                    id:10,
                    FMRadio:"",
                    Loudspeaker:"",
                    AudioJack:""
                },
                Sensors:{
                    id:11,
                    FingerprintSensor:"",
                }
            }
        ]
    },
    {
        id:10,
        name:"",
        price:"",
        description:"",
        img:"",
        specification:[
            {
                id:1,
                keySpec:{
                    id:1,
                    ram:"",
                    Processor:"",
                    RearCamera:"",
                    FrontCamera:"",
                    Battery:"",
                    Display:""
                },
                General:{
                    id:2,
                    LaunchDate:"",
                    OperatingSystem:"",
                    CustomUI:""
                },
                Performance:{
                    id:3,
                    Chipset:"",
                    CPU:"",
                    Architecture:"",
                    Fabrication:"",
                    Graphics:"",
                    RAM:"",
                    RAMType:""
                },
                Display:{
                    id:4,
                    DisplayType:"",
                    ScreenSize:"",
                    Resolution:"",
                    AspectRatio:"",
                    PixelDensity:"",
                    ScreentoBodyRatio:"",
                    ScreenProtection:"",
                    BezelLessdisplay:"",
                    TouchScreen:"",
                    Brightness:"",
                    HDR10HDRsupport:"",
                    RefreshRate:"",
                },
                Design:{
                    id:5,
                    Height:"",
                    Width:"",
                    Thickness:"",
                    Weight:"",
                    BuildMaterial:"",
                    Colours:"",
                    Waterproof:"",
                    Ruggedness:""
                },
                Camera:{
                    id:6,
                    CameraSetup:"",
                    VideoRecording:"",
                    Autofocus:""
                },
                Battery:{
                    id:7,
                    Capacity:"",
                    Type:"",
                    Removable:"",
                    TalkTime:"",
                    WirelessCharging:"",
                    QuickCharging:"",
                    USBTypeC:"",
                },
                Storage:{
                    id:8,
                    InternalMemory:"",
                    ExpandableMemory:"",
                    UserAvailableStorage:"",
                    USBOTG:"",
                    StorageType:""
                },
                NetworkConnectivity:{
                    id:9,
                    SIMSlot:"",
                    SIMSize:"",
                    NetworkSupport:"",
                    VoLTE:"",
                    SIM:"",
                    WiFi:"",
                    Bluetooth:"",
                    GPS:"",
                    NFC:"",
                    USBConnectivity:""
                },
                Multimedia:{
                    id:10,
                    FMRadio:"",
                    Loudspeaker:"",
                    AudioJack:""
                },
                Sensors:{
                    id:11,
                    FingerprintSensor:"",
                }
            }
        ]
    }

]